# .circleci/config.yml
version: 2.1

jobs:
  build-and-test-multi-arch:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: docker info
      - run: |
          git clone https://github.com/seleniumhq-community/docker-seleniarm.git
          cd docker-seleniarm
          git checkout multi-arch-tests
          echo $PWD
      - run: |
          echo "Build Docker images"
          cd docker-seleniarm
          echo $PWD
          export BUILD_DATE=$(date '+%Y%m%d')
          export BRANCH=multi-arch-tests
          VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} ARCH=amd64 make build_multi
      - run: |
          echo "Test Docker images"
          cd docker-seleniarm
          echo $PWD
          export USE_RANDOM_USER=false
          USE_RANDOM_USER_ID=${USE_RANDOM_USER} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} ARCH=arm64 SKIP_BUILD=true make test_multi_arch


workflows:
  build:
    jobs:
      - build-and-test-multi-arch
